### ISSUE TITLE
Add some tests to Compound staking

### ISSUE THREAD

**Issue by BadConfig** [GTON-capital/staking#22]
- [x] Add APY check (After year APY of each user should be correct and APY of all sc the same)
- [x] Add APY check (After n blocks APY of all sc should be correct for these n blocks, as example if for blocks that are equivalent to 1/4 of a year amount of new tokens in the contract should match for each user and all sc)
- [x] Add user dynamic tests (for each user we should emulate several mint and burn actions and calculate APY as in the previous check, compared to real one)
- [x] Add zero tests (if no one farms there should be 0 income at any block after somebody got in, his APY should suite rules)
- [x] Add checks of the APY when it changes in case of users mint and burn actions (for users and contract in total)
- [x] Add checks of the block time parameters in the contract and emulate that it has been changed for some time, the APY should be constant

P.S also when I meant user actions of transferring mint and burn we should use token amount transfer and share transfer
and their correctness check

**Comment by GooGrand** [comment]
#25 Implemented most important tests for apy
