### ISSUE TITLE
Test need to be declared as functions

### ISSUE THREAD

**Issue by sham789** [GTON-capital/staking#32]
There's an issue with tests here. Only one hardcoded value is tested.

Reason:
Tests often fail with specific input values. We need greater coverage with different input values.

Solution:
Tests need to be declared as functions, in order to handle multiple input values, and after all - different test cases.

https://github.com/GTON-capital/GTON-farms-evm/blob/cfd14fc8a3a6ba463c7951e70a41d5eea4ce4021/test/CompoundStaking.test.ts#L220-L262

**Comment by GooGrand** [comment]
Implemented this feature
